### ISSUE TITLE
Cant unpack patched file

### ISSUE THREAD

**Issue by netomx** [bcaller/v380-ipcam-firmware-patch#4]
`RUST_BACKTRACE=full ./patchv380 read 7d00d644b83680522e71794199e95eac.patch
Number of files: 3
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 11, error_len: Some(1) }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x5587cf828df3 - backtrace::backtrace::libunwind::trace::h8cc7bd6ef9eecc96
                               at /usr/src/rustc-1.41.1/vendor/backtrace/src/backtrace/libunwind.rs:88
   1:     0x5587cf828df3 - backtrace::backtrace::trace_unsynchronized::h6d4579bff574314f
                               at /usr/src/rustc-1.41.1/vendor/backtrace/src/backtrace/mod.rs:66
   2:     0x5587cf828df3 - std::sys_common::backtrace::_print_fmt::h90c5eb8ce5c21ab3
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5587cf828df3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd925cae363a8eae6
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5587cf83e4fd - core::fmt::write::h7f27f0f32a72efde
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5587cf828195 - std::io::Write::write_fmt::h248d5ddff30f2014
                               at src/libstd/io/mod.rs:1426
   6:     0x5587cf82ac71 - std::sys_common::backtrace::_print::h998846397d49de77
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5587cf82ac71 - std::sys_common::backtrace::print::he55a1a23a73d03c9
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5587cf82ac71 - std::panicking::default_hook::{{closure}}::h80dc9a42e1547e54
                               at src/libstd/panicking.rs:193
   9:     0x5587cf82a983 - std::panicking::default_hook::h50769e30da5feef3
                               at src/libstd/panicking.rs:210
  10:     0x5587cf82b2ee - std::panicking::rust_panic_with_hook::hd0b3a149883f4cfb
                               at src/libstd/panicking.rs:471
  11:     0x5587cf82ae9e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5587cf840b4e - core::panicking::panic_fmt::h2c5b80195dbe1b07
                               at src/libcore/panicking.rs:84
  13:     0x5587cf83dcb7 - core::result::unwrap_failed::ha1cca7cc6769da6a
                               at src/libcore/result.rs:1188
  14:     0x5587cf635388 - core::result::Result<T,E>::unwrap::h63ed0deaaed40a5b
                               at /usr/src/rustc-1.41.1/src/libcore/result.rs:956
  15:     0x5587cf62e878 - patchv380::read::he701482fa8af3310
                               at src/main.rs:76
  16:     0x5587cf62d63d - patchv380::main::h9ad0c22d770a5240
                               at src/main.rs:37
  17:     0x5587cf626932 - std::rt::lang_start::{{closure}}::h1a6f41098758a684
                               at /usr/src/rustc-1.41.1/src/libstd/rt.rs:67
  18:     0x5587cf82ad33 - std::rt::lang_start_internal::{{closure}}::h76f680a226ff04a4
                               at src/libstd/rt.rs:52
  19:     0x5587cf82ad33 - std::panicking::try::do_call::h299dda570ebabcf7
                               at src/libstd/panicking.rs:292
  20:     0x5587cf82bb5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  21:     0x5587cf821541 - std::panicking::try::hfaf428da211c915f
                               at src/libstd/panicking.rs:270
  22:     0x5587cf821541 - std::panic::catch_unwind::hf2e7b412691ed4fa
                               at src/libstd/panic.rs:394
  23:     0x5587cf821541 - std::rt::lang_start_internal::h3cc876a8b3f40e9c
                               at src/libstd/rt.rs:51
  24:     0x5587cf6268f9 - std::rt::lang_start::h6059f3b0ff4cffd4
                               at /usr/src/rustc-1.41.1/src/libstd/rt.rs:67
  25:     0x5587cf631aca - main
  26:     0x7f14126ea09b - __libc_start_main
  27:     0x5587cf6231ba - _start
  28:                0x0 - <unknown>
`

https://gofile.io/d/qjwWLC

**Comment by bcaller** [comment]
Hi @netomx, Thanks for uploading the patch file.
The issue is that the patch contains long strings of 0xcc instead of null bytes.
I'm preparing an update to fix this now.

**Comment by bcaller** [comment]
Please try the new version.
